### ISSUE TITLE
Unable to restore window size/position on startup

### ISSUE THREAD

**Issue by JulienMaille** [antonypro/QGoodWindow#15]
Hello Antony, nice job with this library.
I was trying to modify `GoodShowCase` example and save/restore the window size and position (using the standard Qt solution to do this) but it does not work with QGoodWindow and the startup position is a bit random.

```c++
MainWindow::MainWindow()
    QSettings settings(QLatin1String("QGoodWindow"), QLatin1String("MainWindow"));
    restoreGeometry(settings.value(QLatin1String("geometry")).toByteArray());
    restoreState(settings.value(QLatin1String("windowState")).toByteArray());
}

MainWindow::~MainWindow()
{
    QSettings settings(QLatin1String("QGoodWindow"), QLatin1String("MainWindow"));
    settings.setValue(QLatin1String("geometry"), saveGeometry());
    settings.setValue(QLatin1String("windowState"), saveState());
}
```

**Comment by antonypro** [comment]
@JulienMaille: It's a missing feature to be implemented in some future version of QGoodWindow.

Thanks.

**Comment by antonypro** [comment]
This issue has been solved in version 2.1.

**Comment by JulienMaille** [comment]
@antonypro have you ever had weird compilation issues with `QtWinExtras\qwinmime.h`?
Your examples compile and run properly with Qt5.15, however with my app it fails to compile like if some includes were missing.
> error C2065: 'FORMATETC': undeclared identifier (compiling source file Tools\QGoodWindow\src\qgoodwindow.cpp)

**Comment by antonypro** [comment]
@JulienMaille: Please provide some minimal code to reproduce the problem. I've never seen this error before.

**Comment by JulienMaille** [comment]
@antonypro it seems it has to do with this line in my .pro file
`DEFINES += WIN32_LEAN_AND_MEAN`
If you add it to ExampleMinimaWindow.pro you will get the same errors

**Comment by antonypro** [comment]
@JulienMaille: Thanks, now I could reproduce the problem. 

However, due to the impact of defining `WIN32_LEAN_AND_MEAN` globally, see: https://stackoverflow.com/q/11040133, `QtWinExtras` becomes broken as you seen. Unfortunately,  `QtWinExtras` is a requirement for use QGoodWindow with Qt 5.

One possible solution is remove this define from the whole app and set it in C++ code specifically where it is necessary, or if it's not necessary remove it completely, in case that you use this define only for improve compilation speed.

Another possible solution if the above solution is not a possibility, is to separate modules, through shared or static libraries, one containing QGoodWindow and another with this define.

This is what I can say to you for now.

Thanks!

**Comment by JulienMaille** [comment]
Thanks for your comment. I will remove that define
