### ISSUE TITLE
`no_qgoodwindow` breaks MSVC linker

### ISSUE THREAD

**Issue by kresimirko** [antonypro/QGoodWindow#22]
As a test, I've tried enabling the `no_qgoodwindow` flag in the ExampleMinimal, ExampleMinimalWindow and GoodShowCase examples and in both I get these linker errors from MSVC:

![image](https://user-images.githubusercontent.com/104278083/211614550-1a32f3ff-75b4-4ee9-9f04-42607a2f9c83.png)

`stylecommon.obj:-1: error: LNK2019: unresolved external symbol __imp_LoadIconW referenced in function "class QPixmap __cdecl StyleCommon::winStandardPixmap(enum QStyle::StandardPixmap)" (?winStandardPixmap@StyleCommon@@YA?AVQPixmap@@W4StandardPixmap@QStyle@@@Z)`

`stylecommon.obj:-1: error: LNK2019: unresolved external symbol __imp_DestroyIcon referenced in function "class QPixmap __cdecl StyleCommon::winStandardPixmap(enum QStyle::StandardPixmap)" (?winStandardPixmap@StyleCommon@@YA?AVQPixmap@@W4StandardPixmap@QStyle@@@Z)`

All three examples work fine without this flag.

Using Qt 6.4.2 on Windows 10.

**Comment by antonypro** [comment]
@kresimirko: The problem is...

https://github.com/antonypro/QGoodWindow/blob/02225cdc922787fab54e6f8ee48d24b85b67be27/QGoodWindow/QGoodWindow/QGoodWindow.pri#L68 

... is set only when QGoodWindow is enabled, preventing the `User32` library to be properly found and linked.

In some circumstances with CMake or Qt 5, the compilation may succeed, probably because the library information is passed somewhere.

The next version will contains the fix for both CMake and QMake, which is basically make the library information to not depend on `no_qgoodwindow` flag.

Thanks for reporting.

**Comment by antonypro** [comment]
This bug was solved on version 2.2.
