### ISSUE TITLE
How to remove maximize button and disable window maximize?

### ISSUE THREAD

**Issue by hcaihao** [antonypro/QGoodWindow#56]
Does qgoodwindow support create a minimize only window which cannot be resized.

**Comment by antonypro** [comment]
Hi, @hcaihao!

I think you are looking for [`QGoodWindow::setFixedSize`](https://github.com/antonypro/QGoodWindow/blob/master/docs/QGoodWindow.md#slot-public-void-setfixedsizeconst-qsize--size) function!

Also a bug that not shows minimize button with fixed size was fixed on version 2.4.4 beta3: https://github.com/antonypro/QGoodWindow/tree/test/QGoodWindow-2.4.4-beta3 .

**Comment by hcaihao** [comment]
will you add an interface to support dialog style window?

**Comment by antonypro** [comment]
@hcaihao:

Actually, the API [QGoodCentralWidget::execDialogWithWindow](https://github.com/antonypro/QGoodWindow/blob/master/docs/QGoodCentralWidget.md#public-static-int-execdialogwithwindowqdialog--dialog-qgoodwindow--parent_gw-qgoodcentralwidget--base_gcw-qwidget--left_title_bar_widget-qwidget--right_title_bar_widget-bool-title_visible-bool-icon_visible) could be used with any `QDialog` based window, not  only `QMessageBox`, the dialog could have fixed size or not, just use this API instead of `dialog.exec()` function.

The return value of this function is the return value of the dialog, like dialog accepted or not.

**Comment by hcaihao** [comment]
Thanks for the tip
