### ISSUE TITLE
#ifdef QGOODWINDOW ?

### ISSUE THREAD

**Issue by PaddleStroke** [antonypro/QGoodWindow#62]
So I can't build. Somehow the numerous `#ifdef` are breaking the build : 
![image](https://github.com/antonypro/QGoodWindow/assets/19984177/502b311d-469a-4efc-b442-6a54c2b8aafd)

See visual studio syntax highlighter shows that there's a syntax problem somewhere in QGoodWindow ctor. Building is giving linker's error  : 

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	LNK2019	unresolved external symbol "public: static void __cdecl QGoodWindow::setup(void)" (?setup@QGoodWindow@@SAXXZ) referenced in function "public: static void __cdecl Gui::Application::runApplication(void)" (?runApplication@Application@Gui@@SAXXZ)	FreeCADGui	C:\Users\Sky_l\Desktop\FC build\src\Gui\Application.obj	1	
> Error	LNK2019	unresolved external symbol "public: bool __cdecl QGoodWindow::close(void)" (?close@QGoodWindow@@QEAA_NXZ) referenced in function "public: void __cdecl Gui::GUIApplication::commitData(class QSessionManager &)" (?commitData@GUIApplication@Gui@@QEAAXAEAVQSessionManager@@@Z)	FreeCADGui	C:\Users\Sky_l\Desktop\FC build\src\Gui\GuiApplication.obj	1	
> Error	LNK2001	unresolved external symbol "public: bool __cdecl QGoodWindow::close(void)" (?close@QGoodWindow@@QEAA_NXZ)	FreeCADGui	C:\Users\Sky_l\Desktop\FC build\src\Gui\CommandDoc.obj	1	
> Error	LNK2001	unresolved external symbol "public: bool __cdecl QGoodWindow::close(void)" (?close@QGoodWindow@@QEAA_NXZ)	FreeCADGui	C:\Users\Sky_l\Desktop\FC build\src\Gui\DlgPreferencesImp.obj	1	

So I'm looking into it to try to understand. And some things I cannot understand. Here for example a block of code : 
```
#ifdef QGOODWINDOW

#ifdef Q_OS_WIN
namespace QGoodWindowUtils
{
class NativeEventFilter;
}
#endif

#if defined Q_OS_WIN || defined Q_OS_LINUX
class Shadow;
#endif

#endif
```

This QGOODWINDOW is used a lot. However nowhere in the code can I see it defined. Meaning that it is disabled everywhere. Same we have 
```
#ifndef QGOODWINDOW
#ifdef Q_OS_WIN
#undef Q_OS_WIN
#endif
#ifdef Q_OS_LINUX
#undef Q_OS_LINUX
#endif
#ifdef Q_OS_MAC
#undef Q_OS_MAC
#endif
#endif
```
Which is undefining Q_OS_WIN and others that are btw used in other places of freecad so there must be some conflicts here as well...

**Comment by antonypro** [comment]
@PaddleStroke:

`QGOODWINDOW` is defined in [QMake](https://github.com/antonypro/QGoodWindow/blob/875ac7baf6512941c60d3363119e8b57a57bec26/QGoodWindow/QGoodWindow/QGoodWindow.pri#L74) and [CMake](https://github.com/antonypro/QGoodWindow/blob/875ac7baf6512941c60d3363119e8b57a57bec26/QGoodWindow/QGoodWindow/QGoodWindow.cmake#L85) build systems files, and in [headers](https://github.com/antonypro/QGoodWindow/blob/875ac7baf6512941c60d3363119e8b57a57bec26/QGoodWindow/QGoodWindow/lib-helper/qgoodwindow_helper.h#L31) if compiling as static or shared library.

It exists because sometimes the user of this library may want to see how their app behaves without `QGoodWindow` with no need to rewrite their whole code.

And about the following code:

```
#ifndef QGOODWINDOW
#ifdef Q_OS_WIN
#undef Q_OS_WIN
#endif
#ifdef Q_OS_LINUX
#undef Q_OS_LINUX
#endif
#ifdef Q_OS_MAC
#undef Q_OS_MAC
#endif
#endif
```

It exists in `qgoodwindow.cpp` only, so it doesn't propagates to whole code that uses this library, it affects `qgoodwindow.cpp` when the user compile the library to behave exactly as `QMainWindow` for the reasons already mentioned.

Thanks!

**Comment by PaddleStroke** [comment]
Thank you for your detailed answer !
I think there is a problem in how I included the library in the project then. Because Ctrl-F through the project was not finding the references you mentioned. Hence my confusion.

I have included the directories in FreeCAD src/gui/CMakeFiles.txt like so : 

```
 include_directories(
     ${CMAKE_BINARY_DIR}
     ${CMAKE_CURRENT_SOURCE_DIR}
     ${CMAKE_CURRENT_SOURCE_DIR}/Quarter
    ${CMAKE_CURRENT_SOURCE_DIR}/QGoodWindow/QGoodWindow
    ${CMAKE_CURRENT_SOURCE_DIR}/QGoodWindow/QGoodCentralWidget
...
```

I'm not very good at cmake and setting up libraries. Per chance could you give me some hints as to how to do it? I added QGoodWindow folders into https://github.com/FreeCAD/FreeCAD/tree/main/src/Gui where it would belong.
But then I am not sure how to include it. Adding it in the CMakeFiles.txt is not the correct way? Freecad is using CMakeFiles.txt, but QGoodWindow is using .cmake files. I'm not sure what is the difference...
