### ISSUE TITLE
Dynamic lib 

### ISSUE THREAD

**Issue by BrnSlr** [antonypro/QGoodWindow#9]
Hi
Thanks for this promising project !
Do you intend by any chance to use QGW as a library ? Is that even possible ?
Thanks

**Comment by antonypro** [comment]
@BrnSlr: Hi, thanks for appreciate this project.

Actually, the way to create a shared library or a static library from this project is creating a bridge library containing `QGoodWindow`.
I maybe add the possibility to compile and use this project directly as library in the future, but for now i can't promise because it adds complexity to the project.

**Comment by BrnSlr** [comment]
Thanks. 
With some changes, i figured it out and will try it now !
